#!/usr/bin/python3

def raise_exception_msg(message=""):
    """NameError exception with a message."""
    raise NameError(message)
